/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

import java.awt.print.PrinterException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author shaikat
 */
public class Restaurants extends javax.swing.JFrame {

     double firstNum;
    double secondNum;
    double result;
    String operations;

    Double[] i = new Double[10];
  
    
     double chic = 0;
    double be = 0;
    double bea = 0;
    double meal = 0;
    
    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
       // jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jcmbCurrency4 = new javax.swing.JComboBox<>();
        jtxtConvert4 = new javax.swing.JTextField();
        jlblConvert4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlblCostDelivery = new javax.swing.JLabel();
        jlblCostMeals = new javax.swing.JLabel();
        jlblCostDrinks = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jbtn7As4 = new javax.swing.JButton();
        jbtn8As7 = new javax.swing.JButton();
        jbtn9As0 = new javax.swing.JButton();
        jbtn10As1 = new javax.swing.JButton();
        jbtn11As8 = new javax.swing.JButton();
        jbtn12As5 = new javax.swing.JButton();
        jbtn13As2 = new javax.swing.JButton();
        jbtn14AsDot = new javax.swing.JButton();
        jbtn15As9 = new javax.swing.JButton();
        jbtn16As6 = new javax.swing.JButton();
        jbtn17As3 = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnDivision = new javax.swing.JButton();
        jbtnMul = new javax.swing.JButton();
        jbtnSubs = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnLeftArrow = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtn26 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jtxtChicBurger = new javax.swing.JTextField();
        jtxtChicBurgerMeal = new javax.swing.JTextField();
        jtxtBCBurger = new javax.swing.JTextField();
        jcmbDrink = new javax.swing.JComboBox<>();
        homeDelivery = new javax.swing.JCheckBox();
        tax = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chickenBurger = new javax.swing.JCheckBox();
        jbeef = new javax.swing.JCheckBox();
        jbea = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        totalBtn = new javax.swing.JButton();
        receipt = new javax.swing.JButton();
        print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Restaurant Management System");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));

        jcmbCurrency4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbCurrency4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One..........", "USA", "Canada", "Indonesia", "Singapore" }));
        jcmbCurrency4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCurrency4ActionPerformed(evt);
            }
        });

        jtxtConvert4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblConvert4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblConvert4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Convert");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setText("Close");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Convert British Dollar Into");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtConvert4)
                        .addComponent(jcmbCurrency4, javax.swing.GroupLayout.Alignment.LEADING, 0, 225, Short.MAX_VALUE)
                        .addComponent(jlblConvert4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcmbCurrency4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtConvert4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblConvert4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sub Total ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tax");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total ");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cost of Drinks ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost of Meal ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of Delivery ");

        jlblCostDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCostMeals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostMeals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jlblCostMeals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCostDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostMeals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 4));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        jbtn7As4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn7As4.setText("4");
        jbtn7As4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7As4ActionPerformed(evt);
            }
        });

        jbtn8As7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn8As7.setText("7");
        jbtn8As7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8As7ActionPerformed(evt);
            }
        });

        jbtn9As0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn9As0.setText("0");
        jbtn9As0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9As0ActionPerformed(evt);
            }
        });

        jbtn10As1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn10As1.setText("1");
        jbtn10As1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn10As1ActionPerformed(evt);
            }
        });

        jbtn11As8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn11As8.setText("8");
        jbtn11As8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn11As8ActionPerformed(evt);
            }
        });

        jbtn12As5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn12As5.setText("5");
        jbtn12As5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn12As5ActionPerformed(evt);
            }
        });

        jbtn13As2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn13As2.setText("2");
        jbtn13As2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn13As2ActionPerformed(evt);
            }
        });

        jbtn14AsDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn14AsDot.setText(".");
        jbtn14AsDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn14AsDotActionPerformed(evt);
            }
        });

        jbtn15As9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn15As9.setText("9");
        jbtn15As9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn15As9ActionPerformed(evt);
            }
        });

        jbtn16As6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn16As6.setText("6");
        jbtn16As6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn16As6ActionPerformed(evt);
            }
        });

        jbtn17As3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtn17As3.setText("3");
        jbtn17As3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn17As3ActionPerformed(evt);
            }
        });

        jbtnEqual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEqual.setText("=");
        jbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEqualActionPerformed(evt);
            }
        });

        jbtnDivision.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDivision.setText("/");
        jbtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivisionActionPerformed(evt);
            }
        });

        jbtnMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnMul.setText("*");
        jbtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMulActionPerformed(evt);
            }
        });

        jbtnSubs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSubs.setText("-");
        jbtnSubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubsActionPerformed(evt);
            }
        });

        jbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnAdd.setText("+");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnLeftArrow.setFont(new java.awt.Font("Wingdings", 0, 24)); // NOI18N
        jbtnLeftArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurant_s/arrowleftc56x56.png"))); // NOI18N
        jbtnLeftArrow.setIconTextGap(2);
        jbtnLeftArrow.setMaximumSize(new java.awt.Dimension(100, 100));
        jbtnLeftArrow.setMinimumSize(new java.awt.Dimension(100, 100));
        jbtnLeftArrow.setPreferredSize(new java.awt.Dimension(100, 100));
        jbtnLeftArrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLeftArrowActionPerformed(evt);
            }
        });

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });

        jbtn26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtn26.setText("+/-");
        jbtn26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisplay)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnLeftArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jbtn7As4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn8As7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn12As5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn11As8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtn15As9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtn16As6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnSubs, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtn10As1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn9As0, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn14AsDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn13As2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jbtn17As3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnLeftArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn26, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn16As6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn12As5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn7As4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSubs, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn15As9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn11As8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn8As7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn17As3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn10As1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtn13As2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn14AsDot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn9As0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Calculator", jPanel7);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receipt", jPanel8);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 4));

        jtxtChicBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChicBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtChicBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChicBurgerActionPerformed(evt);
            }
        });

        jtxtChicBurgerMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChicBurgerMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtBCBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBCBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jcmbDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Drink ..", "Apple Juice", "Coca Cola", "Fanta", "Pepsi", "Ice Tea", "Ice Coffee" }));
        jcmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbDrinkActionPerformed(evt);
            }
        });

        homeDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeDelivery.setText("Home Delivery");
        homeDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeDeliveryMouseClicked(evt);
            }
        });
        homeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeDeliveryActionPerformed(evt);
            }
        });

        tax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tax.setText("Tax");
        tax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taxMouseClicked(evt);
            }
        });
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Drinks");

        chickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chickenBurger.setText("Chicken Burger");
        chickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenBurgerActionPerformed(evt);
            }
        });

        jbeef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbeef.setText("Beef Burger");
        jbeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeefActionPerformed(evt);
            }
        });

        jbea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbea.setText("Bacon & Cheese Burger");
        jbea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbeef)
                            .addComponent(jbea)
                            .addComponent(chickenBurger))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtBCBurger, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jtxtChicBurger)
                            .addComponent(jtxtChicBurgerMeal, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chickenBurger)
                        .addGap(18, 18, 18)
                        .addComponent(jbeef))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtChicBurger)
                        .addGap(13, 13, 13)
                        .addComponent(jtxtChicBurgerMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtBCBurger)
                    .addComponent(jbea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 4));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        totalBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBtn.setText("Total");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });

        receipt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        receipt.setText("Receipt");
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        print.setText("Print the Receipt");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalBtn)
                .addGap(18, 18, 18)
                .addComponent(receipt)
                .addGap(34, 34, 34)
                .addComponent(jbtnReset)
                .addGap(34, 34, 34)
                .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(jbtnExit)
                .addGap(54, 54, 54))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBtn)
                    .addComponent(receipt)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnExit)
                    .addComponent(print))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jcmbCurrency4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCurrency4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbCurrency4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        Double British_Pound = Double.parseDouble(jtxtConvert4.getText());

        if (jcmbCurrency4.getSelectedItem().equals("USA")) {
            String cConvert1 = String.format("$ %.2f", British_Pound * 1.563433929);
            jlblConvert4.setText(cConvert1);
        }
        if (jcmbCurrency4.getSelectedItem().equals("Canada")) {
            String cConvert2 = String.format("CAD %.2f", British_Pound * 1.613946674);
            jlblConvert4.setText(cConvert2);
        }
        if (jcmbCurrency4.getSelectedItem().equals("Indonesia")) {
            String cConvert3 = String.format("IDR  %.2f", British_Pound * 16424.494579549);
            jlblConvert4.setText(cConvert3);
        }
        if (jcmbCurrency4.getSelectedItem().equals("Singapore")) {
            String cConvert1 = String.format("SGD %.2f", British_Pound * 1.986990917);
            jlblConvert4.setText(cConvert1);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void jbtn7As4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7As4ActionPerformed
        //for clearing the textField if it has any value from past
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn7As4.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn7As4ActionPerformed

    private void jbtn8As7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8As7ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn8As7.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn8As7ActionPerformed

    private void jbtn9As0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9As0ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn9As0.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn9As0ActionPerformed

    private void jbtn10As1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn10As1ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn10As1.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn10As1ActionPerformed

    private void jbtn11As8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn11As8ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn11As8.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn11As8ActionPerformed

    private void jbtn12As5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn12As5ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn12As5.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn12As5ActionPerformed

    private void jbtn13As2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn13As2ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn13As2.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn13As2ActionPerformed

    private void jbtn14AsDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn14AsDotActionPerformed
        String EnterNumber = jtxtDisplay.getText() + jbtn14AsDot.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn14AsDotActionPerformed

    private void jbtn15As9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn15As9ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn15As9.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn15As9ActionPerformed

    private void jbtn16As6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn16As6ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn16As6.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn16As6ActionPerformed

    private void jbtn17As3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn17As3ActionPerformed
        if (jtxtDisplay.getText().isEmpty() == false) {
            jtxtDisplay.setText("");
        }

        String EnterNumber = jtxtDisplay.getText() + jbtn17As3.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jbtn17As3ActionPerformed

    private void jbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEqualActionPerformed
        String answer;
        secondNum = Double.parseDouble(jtxtDisplay.getText());
        if (operations == "+") {

            result = firstNum + secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
        } else if (operations == "-") {

            result = firstNum - secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);

        } else if (operations == "*") {

            result = firstNum * secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);

        } else if (operations == "/") {

            result = firstNum / secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);

        } else if (operations == "%") {

            result = firstNum % secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);

        }

        /*   String answer;
        secondNum = Double.parseDouble(jtxtDisplay.getText());
        switch(operations){

            case "+":
            result = firstNum+secondNum;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
            break;

        }
        */
    }//GEN-LAST:event_jbtnEqualActionPerformed

    private void jbtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivisionActionPerformed
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jbtnDivisionActionPerformed

    private void jbtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMulActionPerformed
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jbtnMulActionPerformed

    private void jbtnSubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubsActionPerformed
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jbtnSubsActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        firstNum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jbtnLeftArrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLeftArrowActionPerformed
        String backspace = null;

        if (jtxtDisplay.getText().length() > 0) {
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
            backspace = strB.toString();
            jtxtDisplay.setText(backspace);

        }
    }//GEN-LAST:event_jbtnLeftArrowActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtn26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn26ActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtn26ActionPerformed

    private void jtxtChicBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChicBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChicBurgerActionPerformed

    private void jcmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbDrinkActionPerformed
        // TODO add your handling code here:
        Double apple_juice = 1.20;
        Double coca_cola = 2.10;
        Double fanta = 1.60;
        Double pepsi = 1.40;
        Double ice_tea = 2.50;
        Double ice_coffee = 1.10;

        if (jcmbDrink.getSelectedItem().equals("Apple Juice")) {
            String cApple_juice = String.format("%.2f", apple_juice);
            jlblCostDrinks.setText(cApple_juice);
        }
        if (jcmbDrink.getSelectedItem().equals("Coca Cola")) {
            String cCoca_cola = String.format("%.2f", coca_cola);
            jlblCostDrinks.setText(cCoca_cola);
        }
        if (jcmbDrink.getSelectedItem().equals("Fanta")) {
            String cFanta = String.format("%.2f", fanta);
            jlblCostDrinks.setText(cFanta);
        }
        if (jcmbDrink.getSelectedItem().equals("Pepsi")) {
            String cPepsi = String.format("%.2f", pepsi);
            jlblCostDrinks.setText(cPepsi);
        }
        if (jcmbDrink.getSelectedItem().equals("Ice Tea")) {
            String cIce_tea = String.format("%.2f", ice_tea);
            jlblCostDrinks.setText(cIce_tea);
        }
        if (jcmbDrink.getSelectedItem().equals("Ice Coffee")) {
            String cIce_coffee = String.format("%.2f", pepsi);
            jlblCostDrinks.setText(cIce_coffee);
        }
        if (jcmbDrink.getSelectedItem().equals("Select a Drink ..")) {

            jlblCostDrinks.setText(null);
        }
    }//GEN-LAST:event_jcmbDrinkActionPerformed

    private void homeDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeDeliveryMouseClicked
      /*  Double iDelivery = 3.39;
        if (homeDelivery.isSelected()) {
            String pDelivery = String.format("%.2f", iDelivery);
            jlblCostDelivery.setText(pDelivery);

        } else {
            jlblCostDelivery.setText(null);
        }*/
    }//GEN-LAST:event_homeDeliveryMouseClicked

    private void taxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taxMouseClicked
       /* Double iTax = 0.91;
        if (tax.isSelected()) {
            String pTax = String.format("$ %.2f", iTax);
            jtxtTax.setText(pTax);

        } else {
            jtxtTax.setText(null);

        }*/
    }//GEN-LAST:event_taxMouseClicked

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
       /*  Double iTax = 0.91;
        if (tax.isSelected()) {
            String pTax = String.format("%.2f", iTax);
            jtxtTax.setText(pTax);

        } else {
            jtxtTax.setText(null);

        }  */
       
         double ctotal1 = Double.parseDouble(jlblCostDrinks.getText());
        double ctotal2 = Double.parseDouble(jlblCostMeals.getText());
        double ctotal3 = Double.parseDouble(jlblCostDelivery.getText());
        
        //double ctotal4=Double.parseDouble(jtxtTax.getText());
        
        double taxtotal = (ctotal1+ctotal2+ctotal3)/100;
        
        //String iTotal = new Double(AllTotal).toString();
        String itaxTotal = String.format("%.2f ", taxtotal);
        jtxtTax.setText(itaxTotal);
        
        
    }//GEN-LAST:event_taxActionPerformed

    private void chickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenBurgerActionPerformed
        double Chicken = 1.5;
        if(chickenBurger.isSelected()){
            double cBurger = Double.parseDouble(jtxtChicBurger.getText());
            chic = Chicken * cBurger;
            meal = chic + be + bea;

            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
        double clr = chic;
        if(!chickenBurger.isSelected()){
            meal = meal - clr;
            chic = 0;
            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
    }//GEN-LAST:event_chickenBurgerActionPerformed

    private void jbeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeefActionPerformed
        double Beef = 2.5;
        if(jbeef.isSelected()){
            double bBurger = Double.parseDouble(jtxtChicBurgerMeal.getText());
            be = Beef * bBurger;
            meal = chic + be + bea;

            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
        double cl = be;
        if(!jbeef.isSelected()){
            meal = meal - cl;
            be = 0;
            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
    }//GEN-LAST:event_jbeefActionPerformed

    private void jbeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeaActionPerformed
        double Bea = 3.5;
        if(jbea.isSelected()){
            double bBurger = Double.parseDouble(jtxtBCBurger.getText());
            bea = Bea * bBurger;
            meal = chic + be + bea;

            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
        double cla = bea;
        if(!jbea.isSelected()){
            meal = meal - cla;
            bea = 0;
            String cmeal = String.format("%.2f", meal);
            jlblCostMeals.setText(cmeal);
        }
    }//GEN-LAST:event_jbeaActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        chickenBurger.setSelected(false);
        jbeef.setSelected(false);
        jbea.setSelected(false);
        jtxtChicBurger.setText(null);
        jtxtBCBurger.setText(null);
        jtxtChicBurgerMeal.setText(null);
        tax.setSelected(false);
        homeDelivery.setSelected(false);
        jlblCostDrinks.setText(null);
        jlblCostDelivery.setText(null);
        jlblCostMeals.setText(null);
        jtxtConvert4.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
        jtxtTax.setText(null);
        jlblConvert4.setText(null);

    }//GEN-LAST:event_jbtnResetActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed
        double ctotal1 = Double.parseDouble(jlblCostDrinks.getText());
        double ctotal2 = Double.parseDouble(jlblCostMeals.getText());
        double ctotal3 = Double.parseDouble(jlblCostDelivery.getText());
        
        double ctotal4=Double.parseDouble(jtxtTax.getText());
        
        double subTotal = (ctotal1+ctotal2+ctotal3);
        
        //String iTotal = new Double(AllTotal).toString();
        String isubTotal = String.format("%.2f ", subTotal);
        
        jtxtSubTotal.setText(isubTotal);
        
        
        double total = subTotal+ctotal4;
        
        String itotal = String.format(" %.2f", total);
        
        jtxtTotal.setText(itotal);
        
        
          
        
        
    }//GEN-LAST:event_totalBtnActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void homeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeDeliveryActionPerformed
        // TODO add your handling code here:
         Double iDelivery = 3.39;
        if (homeDelivery.isSelected()) {
            String pDelivery = String.format("%.2f", iDelivery);
            jlblCostDelivery.setText(pDelivery);

        } else {
            jlblCostDelivery.setText(null);
        }
        
    }//GEN-LAST:event_homeDeliveryActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
     double CostOfDrinks=0,CostOfMeals=0,costOfHomeDelivery=0;
        if (jlblCostDrinks.getText().equals(null)) {
            CostOfDrinks=0;
            
        } else {
           CostOfDrinks=Double.parseDouble(jlblCostDrinks.getText());
           
        }
        if (jlblCostMeals.getText().equals(null)) {
            CostOfMeals=0;
            
        } else {
           CostOfMeals=Double.parseDouble(jlblCostMeals.getText());
           
        }
        
        if (jlblCostDelivery.getText().equals(null)) {
            costOfHomeDelivery=0;
            
        } else {
           costOfHomeDelivery=Double.parseDouble(jlblCostDelivery.getText());
           
        }
        double Ta = Double.parseDouble(jtxtTax.getText());
        //double To = Double.parseDouble(jtxtTotal.getText());
        double totalAmount = Double.parseDouble(jtxtTotal.getText());
        
        
         jTextArea1.append("\tRestaurant Management System\n\nCost of Drinks=\t"+CostOfDrinks+" $"
                 +"\n\nCost of Meals=\t"+CostOfMeals+" $"+"\n\nCost of Home Delivery=\t"
                 +costOfHomeDelivery+" $"+"\n Tax Amount=\t\t"+Ta+" $\n"
                 +"\n-----------------------------------------------------------------------------------------\n"
                 +"total amount = \t "+totalAmount+" $");
         
         
         
         
    }//GEN-LAST:event_receiptActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            boolean Complete = jTextArea1.print();
            if(Complete){
                JOptionPane.showMessageDialog(null,"Done Printing","information",JOptionPane.INFORMATION_MESSAGE);
                
            }
            else{
            JOptionPane.showMessageDialog(null,"Printing","Printer",JOptionPane.ERROR_MESSAGE);
            
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chickenBurger;
    private javax.swing.JCheckBox homeDelivery;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JCheckBox jbea;
    private javax.swing.JCheckBox jbeef;
    private javax.swing.JButton jbtn10As1;
    private javax.swing.JButton jbtn11As8;
    private javax.swing.JButton jbtn12As5;
    private javax.swing.JButton jbtn13As2;
    private javax.swing.JButton jbtn14AsDot;
    private javax.swing.JButton jbtn15As9;
    private javax.swing.JButton jbtn16As6;
    private javax.swing.JButton jbtn17As3;
    private javax.swing.JButton jbtn26;
    private javax.swing.JButton jbtn7As4;
    private javax.swing.JButton jbtn8As7;
    private javax.swing.JButton jbtn9As0;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnDivision;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLeftArrow;
    private javax.swing.JButton jbtnMul;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSubs;
    private javax.swing.JComboBox<String> jcmbCurrency4;
    private javax.swing.JComboBox<String> jcmbDrink;
    private javax.swing.JLabel jlblConvert4;
    private javax.swing.JLabel jlblCostDelivery;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblCostMeals;
    private javax.swing.JTextField jtxtBCBurger;
    private javax.swing.JTextField jtxtChicBurger;
    private javax.swing.JTextField jtxtChicBurgerMeal;
    private javax.swing.JTextField jtxtConvert4;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JButton print;
    private javax.swing.JButton receipt;
    private javax.swing.JCheckBox tax;
    private javax.swing.JButton totalBtn;
    // End of variables declaration//GEN-END:variables
}
